version: '2.4'
services:
  app:
    build: .
    image: pablomatheus/purchase-microservice
    container_name: purchase-microservice
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"