server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jackson:
    default-property-inclusion: non_null
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

client:
  united-states-treasury:
    name: united-states-treasury
    base-url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/
