server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jackson:
    default-property-inclusion: non_null
  h2:
    console.enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

client:
  united-states-treasury:
    name: ${CLIENT_UNITED_STATES_TREASURY_NAME}
    base-url: ${CLIENT_UNITED_STATES_TREASURY_URL}
